### ISSUE TITLE
Deploy updated homepage to dev and prod using jx pipelines

### ISSUE THREAD

**Issue by ajpauwels** [pauwels-labs/homepage#2]
Once the /sleep endpoint has been added to the homepage, let's get it deployed.

1. Install jx CLI
2. Go over pipelines and flows
3. Use jx command-line to check pipeline status, re-run pipelines, and promote to prod environment

**Comment by KapDin** [comment]
https://github.com/pauwels-labs/workloads-sdlc-engineering-dev-eu-west-1-cluster/pull/187
https://github.com/pauwels-labs/workloads-sdlc-engineering-dev-eu-west-1-cluster/pull/186

**Comment by ajpauwels** [comment]
Kacper became familiar with:
- The general flow of code through a gitops-based development workflow
- How jx pipelines work and are organized
- How to merge code into an environment from the workloads repo
- How to monitor pipelines via the jx dashboard
